### PR TITLE
:pencil2: Remove whitespace before punctuation marks

### PR DESCRIPTION
**Pull request by NikxDa**

### CODE REVIEW

**Comment by kefranabg** [comment]
Hi @NikxDa thank you for this PR, could you fix tests before I merge ?

**Comment by NikxDa** [comment]
@kefranabg Sorry about that! Test works now, but prettier fails. Can't really tell why though, would appreciate it if you could take a look!

**Comment by NikxDa** [comment]
@kefranabg Got Prettier to work. All done!

**Comment by kefranabg** [comment]
Awesome, thanks for this @NikxDa 👍

**Pull request merged**
