### PR TITLE
:sparkles: Add check for overwrite readme

### PR DESCRIPTION
**Pull request by tbetous**
Add check for overwrite readme #140

### CODE REVIEW

**Comment by tbetous** [comment]
Hi @kefranabg , there is no unit test yet, but I would be glad to have your opinion about my implementation. I'll do tests if you are agree with it.

**Comment by kefranabg** [comment]
Implem looks good to me, I think you can go ahead! I'll do a full review ASAP

**Comment by tbetous** [comment]
Done ! I added tests.

**Comment by kefranabg** [comment]
Thanks buddy

**Pull request merged**
