### PR TITLE
Capacity to read a pom.xml to generate the README

### PR DESCRIPTION
**Pull request by bbonnin**
For old guys like me, that still develop with Maven, it would be great to generate the README.md from a pom.xml instead of a package.json file.

* New command line option: `-x`
```bash
readme -x
```

* The `pom.xml` must contain some informations such as:
```xml
<project>
    <name>My Great Project</name>
    <description>Some useful description</description>
    <url>http://example.com</url>

    <contributors>
        <contributor>
            <name>Bob</name>
        </contributor>
    </contributors>

    <licenses>
        <license>
            <name>MIT</name>
        </license>
    </licenses>

    <issueManagement>
        <url>http://example.com/issues</url>
    </issueManagement>
</project>
```

### CODE REVIEW

**Comment by kefranabg** [comment]
Thanks old man 😉 Cool feature! I'll do a review ASAP

**Comment by patou** [comment]
Why add an cli option, just search if there are a pom.xml or package.json

**Comment by bbonnin** [comment]
In  some cases, on some very weird projects , you can have a pom.xml and package.json in a directory ;)

**Comment by patou** [comment]
Just use a priority of use pom or package, or ask to use wich file use.
For some project, you complexify the use of readme-generator.

**Comment by bbonnin** [comment]
I agree for asking which file to use, but never use a priority, it's error prone !!

**Comment by bbonnin** [comment]
Remove option `-x`, add file detection and asking for which file to use in case of conflict

**Review by patou — APPROVED** [review]
I think it's better with this.

**Pull request closed without merging**
